apiVersion: v1
kind: ConfigMap
metadata:
  name: volatility-config
  labels: {app: volatility-api}
data:
  REDIS_URL: "redis://redis:6379/0"
  SERVE_QUANTIZE: "1"
  PUSHGATEWAY_URL: "pushgateway:9091"
